apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
  labels:
    failure-domain.beta.kubernetes.io/zone: us-central1-a__us-central1-b
spec:
  capacity:
    storage: 10Gi
  accessModes: 
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: my-data-disk
    fsType: ext4