apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80 # this used if other service want to interact with this service
      targetPort: 8080 # this should match the containerPort
